instasohor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('social.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # user activity
    # default feed here
    path('', views.feed, name="feed"),
    # add a post
    path('add-post/', views.addPost, name="addPost"),
    # searching
    path('search/', views.search, name="search"),
    # view a single post
    path('post/<int:id>/', views.post, name="post"),
    # user profile
    path('u/<str:username>/', views.user, name="user"),
    # your profile
    path('profile/', views.profile, name="profile"),
    # edit profile
    path('edit-profile/', views.editProfile, name="editProfile"),
    # show followers
    path('u/<str:username>/followers/', views.followers, name='followers'),
    # show followers
    path('u/<str:username>/following/', views.following, name='following'),
    # toggle follow
    path('toggle-follow/<str:username>/', views.toggleFollow, name='toggleFollow'),
    # single post
    path('p/<int:id>/', views.singlePost, name='singlePost'),
    # comment
    path('c/<int:postId>/', views.comment, name='comment'),
    # like
    path('l/<int:postId>/', views.like, name='like'),
    # delete
    path('d/<int:postId>/', views.delete, name='delete'),

    # authentication
    # register
    path('register/', views.register, name="register"),
]

social/models.py
from django.db import models
from django.contrib.auth.models import User

# User profile created at the time of register using signals
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()
    profile_pic = models.ImageField(
        upload_to='profile_pics/', default="/profile_pics/default.png")

    def __str__(self):
        return str(self.user)

# a single Instasohor post with caption and a image
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    caption = models.TextField(blank=False, null=False)
    image = models.ImageField(upload_to='content/', blank=False, null=False)
    liked_users = models.ManyToManyField(User, related_name="liked_users")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.caption)

# user follower, following relationship maintains
class UserFollowing(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    following_user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers")
    created = models.DateTimeField(auto_now_add=True)

# comment
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.CharField(max_length=450)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.body)

# comment
# like

social/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        ]

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

social/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .decorators import unauthentiated_user
from .models import Profile, Post, UserFollowing, Comment
from django.core.paginator import Paginator

# Home page i.e instasohor feed
# here will show only ur and ur's following's post order by date
@login_required
def feed(request):
    posts = []
    following = [x.following_user_id for x in request.user.following.all()]
    # print(following)
    for post in Post.objects.filter(user__in=following).order_by('-date'):
        posts.append(post)
    for post in Post.objects.filter(user=request.user).order_by('-date'):
        posts.append(post)

    # Paginatior
    p = Paginator(posts, 10)
    page_num = request.GET.get('page', 1)
    try:
        page = p.page(page_num)
    except:
        page = p.page(1)

    context = {'posts': page, 'noOfPages': p.num_pages}
    # print(posts)

    return render(request, 'social/index.html', context)


# Post a image + caption
@login_required
def addPost(request):
    user = request.user

    if request.method == 'POST' and request.FILES.get('image') != None:
        caption = request.POST.get('caption', '')
        Post.objects.create(user=user, caption=caption, image=request.FILES.get('image'))
        return redirect('feed')
    return render(request, 'social/addPost.html')


# A single post that will show all comments/likes
def post(request, id):
    return render(request, 'social/post.html')

# A user profile page
def user(request, username):
    try:
        user = User.objects.get(username=username)
        profile = Profile.objects.get(user=user)
    except:
        return HttpResponse("404 Not found!")

    # if user and user's profile is exists
    n_following = len(user.following.all())
    n_followers = len(user.followers.all())
    context = {'curr_user': user, 'profile': profile, 'n_following':n_following, 'n_followers':n_followers}
    return render(request, 'social/profile.html', context)

# your profile that will simply redirect you
# in your profile page
def profile(request):
    user = request.user    
    return redirect(f'/u/{user.username}')

# you can change your profile pic and bio
@login_required
def editProfile(request):
    user = request.user
    profile = Profile.objects.get(user=user)

    if request.method == 'POST':
        about = request.POST.get('bio', '')
        profile.about = about
        if(request.FILES.get('image') != None):
            profile.profile_pic = request.FILES.get('image')
            print('yes')
        profile.save()
        return redirect(f'/u/{user.username}')
    context = {'profile': profile}
    return render(request, 'social/editProfile.html', context)

# register as a new user
@unauthentiated_user
def register(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('editProfile')

    form = CreateUserForm()
    context = {'registerForm': form}
    return render(request, 'registration/signup.html', context)

# search functionality based on first name, last name, username
def search(request):
    context= {}
    query = request.GET.get('q', '').strip()
    if query != '':
        # search
        results = []
        
        r1 = User.objects.filter(first_name__contains=query)
        r2 = User.objects.filter(last_name__contains=query)
        r3 = User.objects.filter(username__contains=query)
        for i in r1:
            if i not in results:
                results.append(i)
        for i in r2:
            if i not in results:
                results.append(i)
        for i in r3:
            if i not in results:
                results.append(i)
        context = {'query':query, 'results': results}
    
    return render(request, 'social/search.html', context)


# show followers
def followers(request, username):
    try:
        user = User.objects.get(username=username)
        profile = Profile.objects.get(user=user)
    except:
        return HttpResponse("404 Not found!")
    # users followers
    followers = user.followers.all()
    context = {'title': 'Followers', 'results': followers}
    return render(request, 'social/followers.html', context)

# show Following 
def following(request, username):
    try:
        user = User.objects.get(username=username)
        profile = Profile.objects.get(user=user)
    except:
        return HttpResponse("404 Not found!")
    # users followers
    following = user.following.all()
    context = {'title': 'Following', 'results': following}
    return render(request, 'social/following.html', context)


# toogle following /toggle-follow/username
# current user will follow/toggle follow the another user
@login_required
def toggleFollow(request, username):
    try:
        user = User.objects.get(username=username)
        profile = Profile.objects.get(user=user)
    except:
        return HttpResponse("404 Not found!")
    
    # if two person are same then break
    if(request.user == user):
        return redirect('profile')

    # check if relationship already build
    try:
        exists = UserFollowing.objects.get(user_id=request.user, following_user_id=user)
        exists.delete()
    except:
        # build relationship
        UserFollowing.objects.create(user_id=request.user, following_user_id=user)

    return redirect('profile')
    

# single post
def singlePost(request, id):
    try:
        post = Post.objects.get(id=id)
    except:
        return HttpResponse("404 Not found!")

    context = {'post': post}
    return render(request, 'social/post.html', context)

# comment
@login_required
def comment(request, postId):
    try:
        post = Post.objects.get(id=postId)
    except:
        return HttpResponse("404 Not found!")

    if request.method != "POST":
        return HttpResponse("Only POST request Allowed!")
    
    # post request
    comment_body = request.POST.get('comment', '').strip()
    if(comment_body != ''):
        Comment.objects.create(user = request.user, post = post, body=comment_body)
    return redirect('feed')

# like functionality
@login_required
def like(request, postId):
    try:
        post = Post.objects.get(id=postId)
    except:
        return HttpResponse("404 Not found!")
    
    if request.user in post.liked_users.all():
        post.liked_users.remove(request.user)
    else:
        post.liked_users.add(request.user)
        
    return redirect('feed')

    
# delete post
@login_required
def delete(request, postId):
    try:
        Post.objects.get(user = request.user, id=postId).delete()
    except:
        return HttpResponse("404 Not found!")
    return redirect('feed')

social/templates/social/addPost.html
{% extends 'social/base.html' %}
{% load static %}
{% block title %}Instasohor Add Post{% endblock %}
{% block content %}
<div class="container-fluid my-1">
    <div class="row my-3">
        <div class="col-md-6 col-sm-12 m-auto">
            <div class="card">
                <div class="card-header text-center"><h3>Add Post</h3></div>
                <div class="card-body">
                    <form action="{% url 'addPost' %}" method="post"  enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="image">Image</label>
                            <input type="file" class="form-control-file" id="image" name="image" placeholder="Enter Caption..." required>
                        </div>
                        <div class="form-group">
                            <label for="caption">Caption</label>
                            <textarea name="caption" id="caption" cols="30" rows="2" class="form-control" placeholder="Enter caption.." required></textarea>
                        </div>
                        <button type="submit" class="btn btn-success">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

social/templates/social/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">

  <!-- CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div class="grey">
    {% include 'social/header.html' %}
    {% block content %}{% endblock %}
  </div>
  {% include 'social/footer.html' %}
  <!-- Javascripts -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
  {% block js %}{% endblock %}
</body>

</html>

social/templates/social/editProfile.html
{% extends 'social/base.html' %}
{% load static %}
{% block title %}Instasohor Add Post{% endblock %}
{% block content %}
<div class="container-fluid my-1">
    <div class="row my-3">
        <div class="col-md-6 col-sm-12 m-auto">
            <div class="card">
                <div class="card-header text-center"><h3>Edit Profile</h3></div>
                <div class="card-body">
                    <form action="{% url 'editProfile' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="bio">Bio</label>
                            <textarea name="bio" id="bio" cols="30" rows="2" class="form-control" required placeholder="Enter bio..">{{profile.about}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="image">Profile Picture</label>
                            <input type="file" class="form-control-file" id="image" name="image">
                        </div>
                        <button type="submit" class="btn btn-warning">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

social/templates/social/followers.html
{% extends 'social/base.html' %}
{% load static %}
{% block title %}Instasohor {{title}}{% endblock %}
{% block content %}
<div class="container-fluid my-1">
    <div class="row my-3">
        <div class="col-md-6 col-sm-12 m-auto">
            <h3 class="my-3 text-center">{{title}}</h3>
            {% if results|length > 0 %}
            <ul class="list-group">
                {% for result in results %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'user' result.user_id.username %}" class="avatar_link">
                            <img src="{{result.user_id.profile.profile_pic.url}}" alt="Avatar" class="avatar">
                            <span class="avatar_title">{{result.user_id}}</span>
                        </a>
                        <a href="{% url 'toggleFollow' result.user_id.username %}"
                            class="btn btn-sm btn-outline-primary">Follow / UnFollow</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <h3 class="text-center my-3 text-danger">No Result Found!</h3>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

social/templates/social/following.html
{% extends 'social/base.html' %}
{% load static %}
{% block title %}Instasohor {{title}}{% endblock %}
{% block content %}
<div class="container-fluid my-1">
    <div class="row my-3">
        <div class="col-md-6 col-sm-12 m-auto">
            <h3 class="my-3 text-center">{{title}}</h3>
            {% if results|length > 0 %}
            <ul class="list-group">
                {% for result in results %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'user' result.following_user_id.username %}" class="avatar_link">
                            <img src="{{result.following_user_id.profile.profile_pic.url}}" alt="Avatar" class="avatar">
                            <span class="avatar_title">{{result.following_user_id}}</span>
                        </a>
                        <a href="{% url 'toggleFollow' result.following_user_id.username %}"
                            class="btn btn-sm btn-outline-primary">Follow / UnFollow</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <h3 class="text-center my-3 text-danger">No Result Found!</h3>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

social/templates/social/footer.html
<div class="footer bg-dark py-4 text-center text-light small">
    Instasohor &copy; 2021 | Made by <a class="text-light" href="https://sandipsadhukhan.tk" target="_blank"><b> Sandip Sadhukhan</b></a>
</div>

social/templates/social/header.html
{% load static %}
<nav class="navbar navbar-expand sticky-top navbar-light bg-light m-0">
    <div class="container">
        <a class="navbar-brand" href="{% url 'feed' %}"><img src="{% static 'images/favicon.png' %}" class="mr-2 brand-image" alt="Logo"> <span class="title"> Instasohor</span></a>
        <div>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed' %}" data-toggle="tooltip" data-placement="bottom" title="Feed"><i
                            class="fa fa-home fa-2x"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'addPost' %}" data-toggle="tooltip" data-placement="bottom" title="Add Post"><i
                            class="fa fa-plus-square fa-2x"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}" data-toggle="tooltip" data-placement="bottom" title="Your profile"><img src="{{user.profile.profile_pic.url}}" alt="Avatar" class="avatar_small"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search' %}" data-toggle="tooltip" data-placement="bottom" title="Search"><i
                            class="fa fa-search fa-2x"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}" data-toggle="tooltip" data-placement="bottom" title="Logout"><i
                            class="fa fa-sign-out fa-2x"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}" data-toggle="tooltip" data-placement="bottom" title="Login"><i
                            class="fa fa-sign-in fa-2x"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}" data-toggle="tooltip" data-placement="bottom" title="Register"><i
                            class="fa fa-user-plus fa-2x"></i></a>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>

social/templates/social/index.html
{% extends 'social/base.html' %}
{% load static %}
{% block title %}Instasohor Feed{% endblock %}
{% block content %}
<div class="container-fluid my-1">
    {% for post in posts %}
    <div class="row my-3">
        <div class="col-md-6 col-sm-12 m-auto">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'user' post.user.username %}" class="avatar_link">
                            <img src="{{post.user.profile.profile_pic.url}}" alt="Avatar" class="avatar">
                            <span class="avatar_title">{{post.user.username}}</span>
                        </a>
                        {% if post.user.username != user.username %}
                        <a href="{% url 'toggleFollow' post.user.username %}"
                            class="btn btn-sm btn-outline-primary">Follow / UnFollow</a>
                        {% else %}
                        <a href="{% url 'delete' post.id %}"
                            class="btn btn-sm btn-outline-danger" data-toggle="tooltip" data-placement="left" title="Delete Post"><i class="fa fa-2x fa-trash"></i></a>
                        {% endif %}
                    </div>
                </div>
                <img class="card-img-top" src="{{post.image.url}}" alt="Card image cap">
                <div class="card-body">
                    <div><a href="{% url 'like' post.id %}" class=" text-danger"><i
                                class="fa fa-heart{% if user not in post.liked_users.all %}-o{% endif %} fa-2x"></i></a>
                    </div>
                    <div class="mb-2"><b>{{post.liked_users.all | length}} like{% if post.liked_users.all|length > 1 %}s{% endif %}</b></div>
                    <a href="{% url 'singlePost' post.id %}" class="caption_link">
                        <p class="card-text text-left mb-1 caption">{{post.caption}}</p>
                        <div class="comments">
                            {% for comment in post.comment_set.all|slice:"3" %}
                            <div class="comment">
                                <b>{{comment.user}}</b> <span> {{comment.body}}</span>
                            </div>
                            {% endfor %}
                        </div>
                    </a>
                </div>
                <div class="card-footer">
                    {% if user.is_authenticated %}
                    <form action="{% url 'comment' post.id %}" method="POST">
                        {% csrf_token %}
                        <div class="d-flex">
                            <input name="comment" type="text" class="form-control" placeholder="Add a comment...">
                            <button type="submit" class="ml-2 btn btn-success">Post</button>
                        </div>
                    </form>
                    {% else %}
                    <h4>You Have to Login to comment</h4>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'feed' %}?page={{posts.previous_page_number}}" tabindex="-1"><i
                        class="fa fa-arrow-left"></i></a>
            </li>
            {% endif %}
            {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'feed' %}?page={{posts.next_page_number}}"><i
                        class="fa fa-arrow-right"></i></a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

social/templates/social/post.html
{% extends 'social/base.html' %}
{% load static %}
{% block title %}Instasohor Feed{% endblock %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-md-10 col-sm-12 mx-auto">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between">
                                <a href="{% url 'user' post.user.username %}" class="avatar_link">
                                    <img src="{{post.user.profile.profile_pic.url}}" alt="Avatar" class="avatar">
                                    <span class="avatar_title">{{post.user.username}}</span>
                                </a>
                                {% if post.user.username != user.username %}
                                <a href="{% url 'toggleFollow' post.user.username %}"
                                    class="btn btn-sm btn-outline-primary">Follow / UnFollow</a>
                                {% else %}
                                <a href="{% url 'delete' post.id %}" class="btn btn-sm btn-outline-danger"
                                    data-toggle="tooltip" data-placement="left" title="Delete Post"><i
                                        class="fa fa-2x fa-trash"></i></a>
                                {% endif %}
                            </div>
                        </div>
                        <img class="card-img-top" src="{{post.image.url}}" alt="Card image cap">
                        <div class="card-body">
                            <div><a href="{% url 'like' post.id %}" class=" text-danger"><i
                                        class="fa fa-heart{% if user not in post.liked_users.all %}-o{% endif %} fa-2x"></i></a>
                            </div>
                            <div class="mb-2"><b>{{post.liked_users.all | length}} like{% if post.liked_users.all|length > 1 %}s{% endif %}</b></div>
                            <p class="card-text text-left mb-1 caption">{{post.caption}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            {% if user.is_authenticated %}
                            <form action="{% url 'comment' post.id %}" method="POST">
                                {% csrf_token %}
                                <div class="d-flex">
                                    <input name="comment" type="text" class="form-control"
                                        placeholder="Add a comment...">
                                    <button type="submit" class="ml-2 btn btn-success">Post</button>
                                </div>
                            </form>
                            {% else %}
                            <h4>You Have to Login to comment</h4>
                            {% endif %}
                            <div class="comments my-4" style="max-height: 50vh; overflow:auto;">
                                <div class="comments">
                                    {% for comment in post.comment_set.all %}
                                    <div class="comment">
                                        <b>{{comment.user}}</b> <span> {{comment.body}}</span>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

social/templates/social/profile.html
{% extends 'social/base.html' %}
{% load static %}
{% block title %}Instasohor {{curr_user.username}}{% endblock %}
{% block content %}
<div class="container my-1 py-4 profile">
    <div class="row">
        <div class="col-md-8 col-sm-12 m-auto">
            <div class="row">
                <div class="col-md-6 col-sm-12 text-center">
                    <img src="{{profile.profile_pic.url}}"
                        alt="Avatar" class="avatar_profile">
                </div>
                <div class="col-md-6 col-sm-12">
                    <h2 class="my-2 username-heading">{{curr_user.username}}
                        {% if curr_user.username == user.username %}
                        <a href="{% url 'editProfile' %}" class="btn btn-secondary">Edit Profile</a>
                        {% else %}
                        <a href="{% url 'toggleFollow' curr_user.username %}" class="btn btn-sm btn-outline-primary">Follow / UnFollow</a>
                        {% endif %}
                    </h2>
                    <div class="my-3 d-flex justify-content-between">
                        <div><b>{{curr_user.post_set.all|length}}</b> post{% if curr_user.post_set.all|length > 1 %}s{% endif %}</div>
                        <div>
                            <a href="{% url 'followers' curr_user.username %}" class="text-dark">
                                <b>{{n_followers}}</b> follower{% if n_followers > 1 %}s{% endif %}
                            </a>
                        </div>
                        <div>
                            <a href="{% url 'following' curr_user.username %}" class="text-dark">
                                <b>{{n_following}}</b> following{% if n_following > 1 %}s{% endif %}
                            </a>
                        </div>
                    </div>
                    <p class="mt-4 mb-1"><b>{{curr_user.first_name}} {{curr_user.last_name}}</b></p>
                    <p>{{profile.about}}</p>
                </div>
            </div>
        </div>
    </div>
    <hr class="mt-4">
    <div class="text-center">
        <h3 class="my-3">All Posts</h3>
        <div class="row">
            <div class="col-md-9 col-sm-12 mx-auto">
                <div class="row">
                    {% for post in curr_user.post_set.all %}
                    <div class="col-md-4 col-sm-12 my-2">
                        <a href="{% url 'singlePost' post.id %}">
                            <img class="img-thumbnail img-fluid"
                                src="{{post.image.url}}">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}